
global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true