groups:
- name: alert.rules  
rules:
- alert: InstanceDown
  expr: up==0
  for: 1m
  labels:
    severity: "critical"
annotations:
  summary:  "Endpoint {{$labels.instance}}"
  identifier: "{{$labels.instance}}"
  description: "{{$labels.instance}} of job {{$labels.job}} has been down for more than 1 min