alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['host.docker.internal:8080']

  - job_name: 'backend'
    static_configs:
    - targets: [localhost:8000]