# Generated by Django 4.0.3 on 2024-01-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloverfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
