# Generated by Django 4.0.3 on 2024-01-15 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloverfeed', '0002_alter_authuser_options_alter_authuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresult',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='form',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='feedback_id',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question_id',
        ),
        migrations.AddField(
            model_name='feedbackresult',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloverfeed.form'),
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloverfeed.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloverfeed.form'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='feedback',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloverfeed.feedbackresult'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloverfeed.question'),
        ),
    ]
