# Generated by Django 4.0.3 on 2024-01-15 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloverfeed', '0003_remove_feedbackresult_form_id_remove_form_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresult',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloverfeed.form'),
        ),
        migrations.AlterField(
            model_name='form',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='multiplechoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloverfeed.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloverfeed.form'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloverfeed.feedbackresult'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloverfeed.question'),
        ),
    ]
