# Generated by Django 4.0.3 on 2024-01-15 14:21

import cloverfeed.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloverfeed", "0004_alter_feedbackresult_form_alter_form_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="user_id",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
