# Generated by Django 4.0.3 on 2024-01-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloverfeed', '0004_alter_feedbackresult_form_alter_form_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
