# Generated by Django 4.0.3 on 2024-01-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloverfeed', '0005_authuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='user_id',
        ),
    ]
