# Generated by Django 4.0.3 on 2024-01-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloverfeed', '0005_alter_authuser_id'),
        ('cloverfeed', '0006_remove_authuser_user_id'),
    ]

    operations = [
    ]
